from __future__ import annotations

from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np


def fit_pure_quadratic(
    x: np.ndarray,
    y: np.ndarray,
    weights: np.ndarray | None = None,
) -> float:
    """
    Fit y ≈ a * x^2 by weighted least squares.
    """
    mask = np.isfinite(x) & np.isfinite(y) & (x <= 0.60) & (x >= -0.60)
    x = x[mask]
    y = y[mask]

    z = x**2

    if weights is None:
        denom = np.sum(z**2)
        if denom <= 1e-15:
            return float("nan")
        a = np.sum(z * y) / denom
    else:
        w = weights[mask]
        denom = np.sum(w * z**2)
        if denom <= 1e-15:
            return float("nan")
        a = np.sum(w * z * y) / denom

    return float(a)


# def plot_sq_logit_diff_with_intervals(
#     cfg, bin_centers, stats_full, setting_full, out_path
# ):
#     plt.figure(figsize=(8, 5))

#     for confidence_level, stats in stats_full.items():

#         mean = stats["sq_logit_diff"]["mean"]
#         stderr = stats["sq_logit_diff"]["stderr"]

#         label_addition = (
#             f", deleted prob is {confidence_level}" if confidence_level else ""
#         )

#         plt.plot(
#             bin_centers,
#             mean,
#             label=f"unlearning with {cfg.unlearning_method}{label_addition}",
#         )
#         plt.fill_between(
#             bin_centers,
#             mean - stderr,
#             mean + stderr,
#             alpha=0.25,
#         )

#         if "full_sq_logit_diff" in stats:
#             full_mean = stats["full_sq_logit_diff"]["mean"]
#             full_stderr = stats["full_sq_logit_diff"]["stderr"]
#             plt.plot(bin_centers, full_mean, label=f"before unlearning{label_addition}")
#             plt.fill_between(
#                 bin_centers,
#                 full_mean - full_stderr,
#                 full_mean + full_stderr,
#                 alpha=0.2,
#             )

#         # if cfg.n_delete > 1:
#         #     setting = setting_full[confidence_level]
#         #     x_s = setting["x_s"]
#         #     x_a = setting["x_a"]

#         #     rhos = x_s @ x_a
#         #     rho_min, rho_max = np.min(rhos), np.max(rhos)

#         #     plt.axvspan(rho_min, rho_max, alpha=0.1, label=f"X_s{label_addition}")

#     plt.xlabel(r"$\dfrac{\langle x, x_f \rangle}{\|x_f\|^2}$")
#     plt.ylabel(r"Mean $(\Delta \mathrm{logit})^2$")
#     plt.title(f"Squared logit gap by ripple interval: {cfg.model_type} regression")
#     plt.legend()
#     plt.grid(alpha=0.3)
#     plt.tight_layout()
#     plt.savefig(out_path)
#     plt.close()


def plot_sq_logit_diff_heatmap(bin_centers, all_runs_matrix, out_path, title):
    plt.figure(figsize=(10, 6))

    extent = [bin_centers[0], bin_centers[-1], 0, all_runs_matrix.shape[0]]

    plt.imshow(
        all_runs_matrix,
        aspect="auto",
        origin="lower",
        extent=extent,
    )
    plt.colorbar(label=r"Mean $(\Delta \mathrm{logit})^2$ in bin")

    plt.xlabel(r"$\dfrac{\langle x, x_f \rangle}{\|x_f\|^2}$")
    plt.ylabel("Run index")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_path)
    plt.close()


def plot_flip_rate_with_intervals(cfg, bin_centers, stats_full, setting_full, out_path):
    fig, ax = plt.subplots(figsize=(8, 5))
    _plot_flip_rate_on_ax(ax, cfg, bin_centers, stats_full)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def plot_logit_variance(cfg, bin_centers, stats_full, setting_full, out_path):
    fig, ax = plt.subplots(figsize=(8, 5))
    _plot_logit_variance_on_ax(ax, cfg, bin_centers, stats_full)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def plot_polar_heatmap(
    x_a: np.ndarray,
    theta_unlearn: np.ndarray,
    theta_retrain: np.ndarray,
    out_path: str | Path,
    r_max: float = 2.0,
    n_r: int = 200,
    n_theta: int = 360,
    seed: int = 42,
    title: str | None = None,
) -> None:
    """
    Plot a full polar heatmap over synthetic points x_b generated by
    polar coordinates relative to x_a.

    We choose a 2D plane spanned by:
        u = x_a / ||x_a||
        v = random unit vector orthogonal to u

    Then for each (r, theta), theta in [0, 2*pi), we construct
        x_b(r, theta) = r * (cos(theta) * u + sin(theta) * v)

    and plot
        (logit_unlearn(x_b) - logit_retrain(x_b))^2.
    """
    out_path = Path(out_path)

    x_a_norm = np.linalg.norm(x_a)
    if x_a_norm <= 1e-15:
        raise ValueError("x_a has near-zero norm.")

    u = x_a / x_a_norm

    rng = np.random.default_rng(seed)
    v = rng.normal(size=u.shape[0])
    v = v - (v @ u) * u
    v_norm = np.linalg.norm(v)

    max_retries = 50
    retry = 0
    while v_norm <= 1e-12 and retry < max_retries:
        v = rng.normal(size=u.shape[0])
        v = v - (v @ u) * u
        v_norm = np.linalg.norm(v)
        retry += 1

    if v_norm <= 1e-12:
        raise ValueError("Failed to construct a direction orthogonal to x_a.")

    v = v / v_norm

    # Full polar grid
    r = np.linspace(0.0, r_max, n_r)
    theta = np.linspace(0.0, 2.0 * np.pi, n_theta, endpoint=False)
    Theta, R = np.meshgrid(theta, r, indexing="xy")

    # x_b(r, theta)
    X = (
        R[..., None] * np.cos(Theta)[..., None] * u[None, None, :]
        + R[..., None] * np.sin(Theta)[..., None] * v[None, None, :]
    )

    unlearn_logits = X @ theta_unlearn
    retrain_logits = X @ theta_retrain
    Z = (unlearn_logits - retrain_logits) ** 2

    fig, ax = plt.subplots(figsize=(8, 7), subplot_kw={"projection": "polar"})

    mesh = ax.pcolormesh(Theta, R, Z, shading="auto")
    cbar = plt.colorbar(mesh, ax=ax, pad=0.1)
    cbar.set_label(r"$(\Delta \mathrm{logit})^2$")

    # theta = 0 is the direction of x_a
    ax.set_theta_zero_location("E")
    ax.set_theta_direction(1)

    # Mark x_a direction and opposite direction
    ax.plot(
        [0.0, 0.0],
        [0.0, r_max],
        linestyle="--",
        linewidth=1.5,
        color="white",
        alpha=0.9,
    )
    ax.plot(
        [np.pi, np.pi],
        [0.0, r_max],
        linestyle="--",
        linewidth=1.0,
        color="white",
        alpha=0.7,
    )

    # Mark the circle of radius ||x_a||
    angles = np.linspace(0.0, 2.0 * np.pi, 400)
    ax.plot(
        angles,
        np.full_like(angles, x_a_norm),
        linestyle="--",
        linewidth=1.0,
        color="white",
        alpha=0.8,
    )

    if title is None:
        title = "Polar heatmap of squared logit difference"
    ax.set_title(title, pad=20)

    plt.tight_layout()
    plt.savefig(out_path, bbox_inches="tight")
    plt.close()


def plot_graphs(cfg, bin_centers, stats_full, setting_full):

    plot_dir = Path(cfg.out_dir)
    plot_dir.mkdir(parents=True, exist_ok=True)

    # 1) Main curve: mean squared logit gap by ripple interval
    plot_sq_logit_diff_with_intervals(
        cfg,
        bin_centers,
        stats_full,
        setting_full,
        plot_dir / "sq_logit_diff_with_ci.pdf",
    )

    for condidence_level, setting in setting_full.items():

        condidence_level_label = condidence_level or ""
        # 2) Heatmap over runs x ripple bins
        plot_polar_heatmap(
            x_a=setting["x_a"],
            theta_unlearn=setting["theta_unlearn"],
            theta_retrain=setting["theta_retrain"],
            out_path=plot_dir / f"polar_heatmap{condidence_level_label}.pdf",
            r_max=2 * np.linalg.norm(setting["x_a"]),
            seed=cfg.seed,
            title=f"Polar heatmap: {cfg.model_type}, {cfg.unlearning_method}",
        )

    if cfg.model_type == "logistic":
        # 3) Flip label probability by ripple interval
        plot_flip_rate_with_intervals(
            cfg,
            bin_centers,
            stats_full,
            setting_full,
            plot_dir / "flip_rate_with_ci.pdf",
        )

        # 4) Variance of logit shift by ripple interval
        plot_logit_variance(
            cfg,
            bin_centers,
            stats_full,
            setting_full,
            plot_dir / "logit_variance.pdf",
        )

        plot_rl_flip_and_variance(
            cfg,
            bin_centers,
            stats_full,
            setting_full,
            plot_dir / "rl_flip_and_variance.pdf",
        )


def _plot_sq_logit_diff_on_ax(ax, cfg, bin_centers, stats_full, setting_full):

    method_official_names = {
        "ga": "Gradient Ascent",
        "rl": "Random Labels",
    }

    for confidence_level, stats in stats_full.items():

        mean = stats["sq_logit_diff"]["mean"]
        stderr = stats["sq_logit_diff"]["stderr"]

        label_addition = (
            f", deleted prob is {confidence_level}" if confidence_level else ""
        )

        (line,) = ax.plot(
            bin_centers,
            mean,
            label=f"{method_official_names[cfg.unlearning_method]}{label_addition}",
            color="#4C78A8",
        )
        curve_color = line.get_color()

        ax.fill_between(
            bin_centers,
            mean - stderr,
            mean + stderr,
            alpha=0.25,
            color=curve_color,
        )

        deleted_stats = stats.get("deleted_point_sq_logit_diff")
        if deleted_stats is not None and cfg.unlearning_method == "ga":
            deleted_mean = deleted_stats["mean"]
            deleted_stderr = deleted_stats["stderr"]
            deleted_rho = deleted_stats.get("rho", 1.0)
            ax.errorbar(
                [deleted_rho],
                [deleted_mean],
                yerr=[2 * deleted_stderr],
                fmt="o",
                color=curve_color,
                mfc="white",
                mec=curve_color,
                capsize=3,
                elinewidth=1.0,
                zorder=5,
            )


            ax.annotate(
                r"$x_f$",
                (deleted_rho, deleted_mean),
                xytext=(6, 4),
                textcoords="offset points",
                color=curve_color,
                fontsize=10,
            )

        if "full_sq_logit_diff" in stats:
            full_mean = stats["full_sq_logit_diff"]["mean"]
            full_stderr = stats["full_sq_logit_diff"]["stderr"]
            ax.plot(
                bin_centers,
                full_mean,
                color="green",
                label=f"Before unlearning{label_addition}",
            )
            ax.fill_between(
                bin_centers,
                full_mean - full_stderr,
                full_mean + full_stderr,
                alpha=0.2,
            )

    if cfg.unlearning_method == "ga":
        ax.set_ylabel(r"Mean squared logit difference")
        
    ax.set_xlabel(r"$\dfrac{\langle x_q, x_f \rangle}{\|x_f\|^2}$")
    ax.grid(alpha=0.3)


def plot_sq_logit_diff_with_intervals(
    cfg, bin_centers, stats_full, setting_full, out_path
):
    fig, ax = plt.subplots(figsize=(8, 5))
    _plot_sq_logit_diff_on_ax(ax, cfg, bin_centers, stats_full, setting_full)
    ax.set_title(f"Squared logit gap by ripple interval: {cfg.model_type} regression")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def plot_sq_logit_diff_comparison(method_results, bin_centers, out_path):
    fig, axes = plt.subplots(
        1,
        len(method_results),
        figsize=(11, 3),
        sharey=False,
    )

    if len(method_results) == 1:
        axes = [axes]

    method_official_names = {
        "GA": "Gradient Ascent",
        "RL": "Random Labels",
    }

    for ax, (method_name, (cfg, stats_full, setting_full)) in zip(
        axes, method_results.items()
    ):

        _plot_sq_logit_diff_on_ax(ax, cfg, bin_centers, stats_full, setting_full)
        ax.set_title(
            f"{method_official_names[method_name]} + {cfg.model_type} regression"
        )
        ax.legend(fontsize=12)

    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def _plot_flip_rate_on_ax(ax, cfg, bin_centers, stats_full):

    official_method_names = {
        "ga": "Gradient Ascent",
        "rl": "Random Labels",
    }
    for confidence_level, stats in stats_full.items():
        mean = stats["flip_rate"]["mean"]
        stderr = stats["flip_rate"]["stderr"]

        label_addition = (
            f", deleted prob is {confidence_level}" if confidence_level else ""
        )

        ax.plot(
            bin_centers,
            mean,
            label=f"{official_method_names[cfg.unlearning_method]}{label_addition}",
        )
        ax.fill_between(
            bin_centers,
            mean - stderr,
            mean + stderr,
            alpha=0.25,
        )

        if "full_flip_rate" in stats:
            full_mean = stats["full_flip_rate"]["mean"]
            full_stderr = stats["full_flip_rate"]["stderr"]
            ax.plot(
                bin_centers,
                full_mean,
                label=f"Before unlearning{label_addition}",
            )
            ax.fill_between(
                bin_centers,
                full_mean - full_stderr,
                full_mean + full_stderr,
                alpha=0.2,
            )

    ax.set_xlabel(r"$\dfrac{\langle x_q, x_f \rangle}{\|x_f\|^2}$")
    ax.set_ylabel("Flip probability")
    ax.set_title("Label flip rate by ripple interval")
    ax.grid(alpha=0.3)


def _plot_logit_variance_on_ax(ax, cfg, bin_centers, stats_full):
    for confidence_level, stats in stats_full.items():
        label_addition = (
            f", deleted prob is {confidence_level}" if confidence_level else ""
        )

        mean = stats["delta_logit_var"]["mean"]
        stderr = stats["delta_logit_var"]["stderr"]

        plt.plot(
            bin_centers,
            mean,
            label=rf"Var(logit shift){label_addition}",
        )
        plt.fill_between(
            bin_centers,
            mean - stderr,
            mean + stderr,
            alpha=0.25,
        )
    ax.set_xlabel(r"$\dfrac{\langle x_q, x_f \rangle}{\|x_f\|^2}$")
    ax.set_ylabel(r"$\mathrm{Var}(\Delta \mathrm{logit})$")
    ax.set_title("Variance of logit shift by ripple interval")
    ax.grid(alpha=0.3)


def plot_rl_flip_and_variance(cfg, bin_centers, stats_full, setting_full, out_path):
    fig, axes = plt.subplots(
        1,
        2,
        figsize=(13, 5),
        sharex=True,
        sharey=False,
    )

    ax_left, ax_right = axes

    _plot_logit_variance_on_ax(ax_right, cfg, bin_centers, stats_full)
    _plot_flip_rate_on_ax(ax_left, cfg, bin_centers, stats_full)

    ax_left.legend()
    ax_right.legend()

    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def plot_rl_flip_and_variance_fixed_xa(
    cfg,
    bin_centers,
    stats_full,
    out_path,
):
    fig, axes = plt.subplots(
        1,
        2,
        figsize=(13, 5),
        sharex=True,
        sharey=False,
    )

    ax_var, ax_flip = axes

    label_map = {
        "low": r"low x_f conf $\in [0.50, 0.65]$",
        "mid": r"mid x_f conf $\in [0.65, 0.80]$",
        "high": r"high x_f conf $\in [0.80, 1.0]$",
        None: r"all deleted points",
    }

    for confidence_level, stats in stats_full.items():
        label = label_map[confidence_level]

        var_mean = stats["delta_logit_var_fixed_xa"]["mean"]
        var_stderr = stats["delta_logit_var_fixed_xa"]["stderr"]

        ax_var.plot(bin_centers, var_mean, label=label)
        ax_var.fill_between(
            bin_centers,
            var_mean - var_stderr,
            var_mean + var_stderr,
            alpha=0.25,
        )

        flip_mean = stats["flip_prob_fixed_xa"]["mean"]
        flip_stderr = stats["flip_prob_fixed_xa"]["stderr"]

        ax_flip.plot(bin_centers, flip_mean, label=label)
        ax_flip.fill_between(
            bin_centers,
            flip_mean - flip_stderr,
            flip_mean + flip_stderr,
            alpha=0.25,
        )

    ax_var.set_xlabel(r"$\dfrac{\langle x, x_f \rangle}{\|x_f\|^2}$")
    ax_var.set_ylabel(r"Mean $\mathrm{Var}(\Delta \mathrm{logit})$")
    ax_var.set_title(r"Variance of $\Delta \mathrm{logit}$")
    ax_var.grid(alpha=0.3)
    ax_var.legend()

    ax_flip.set_xlabel(r"$\dfrac{\langle x, x_f \rangle}{\|x_f\|^2}$")
    ax_flip.set_ylabel("Probability of disagreement with retrain")
    ax_flip.set_title("Prediction disagreement with retrain")
    ax_flip.grid(alpha=0.3)
    ax_flip.legend()

    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)
